import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "../styles/index.css";
import ThemeProvider from "@/providers/ThemeProvider";
import StoreProvider from "@/providers/StoreProvider";
import TranslationProvider from "@/providers/TranslationProvider";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import { Toaster } from "sonner";

const font = Raleway({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Housy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={font.className}>
      <body className="bg-bg-1 md:bg-bg-2">
        <ReactQueryProvider>
          <StoreProvider>
            <ThemeProvider>
              <TranslationProvider>
                {children}
                <Toaster position="bottom-center" />
              </TranslationProvider>
            </ThemeProvider>
          </StoreProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
